version: "3"
services:
  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    restart: unless-stopped
    command: -tou-accept -email <email> -pass <password> -device <devicename>